# Generated by Django 5.2.6 on 2025-09-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('baseball', 'Baseball'), ('football', 'Football'), ('basketball', 'Basketball')], max_length=50, verbose_name='sport_name'),
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
