# Generated by Django 5.2.6 on 2025-11-02 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_alter_team_sport_delete_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters only.', max_length=150, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]+$')], verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters only.', max_length=150, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]+$')], verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters only.', max_length=150, validators=[django.core.validators.RegexValidator(message='Only letters and numerics are allowed.', regex='^[A-Za-z0-9 ]+$')], verbose_name='team_name'),
        ),
    ]
