# Generated by Django 5.2.6 on 2026-01-03 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_alter_player_first_name_alter_player_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
